#!/bin/sh

# --> PAM_SERVICE='lightdm'

# verificare se serve ancora ########
mkdir -p -m 700 /run/user/${PAM_USER} 2>/dev/null
chown ${PAM_USER} /run/user/${PAM_USER} 2>/dev/null
#####################################

WPACONF=/run/user/${PAM_USER}/wpa_supplicant.conf

. /etc/livenet/livenet.conf

[ "${livenet_8021x}" = "true" ] || exit 1

if [ "${PAM_SERVICE}" = "login" ] || [ "${PAM_SERVICE}" = "gdm-password" ] || [ "${PAM_SERVICE}" = "lightdm" ]; then
    if [ -f /etc/wpa_supplicant.conf ]; then
        echo "$(eval "echo \"$(cat /etc/wpa_supplicant.conf)\"")" > ${WPACONF}
        chown ${PAM_USER} ${WPACONF}
    fi
fi

# to allow deny of login (with exit 0 user can enter with wrong password!!!)
exit 1
