#!/bin/sh

# --> PAM_SERVICE='lightdm'

mkdir -p -m 700 /run/user/${PAM_USER}
chown ${PAM_USER} /run/user/${PAM_USER}
WPACONF=/run/user/${PAM_USER}/wpa_supplicant.conf

. /etc/livenet/livenet.conf

if [ "${livenet_8021x}" = "true" ] && [ "${PAM_SERVICE}" = "lightdm" ]; then
    if [ -f /etc/wpa_supplicant.conf ]; then
        echo "$(eval "echo \"$(cat /etc/wpa_supplicant.conf)\"")" > ${WPACONF}
        chown ${PAM_USER} ${WPACONF}
    fi
fi

exit 0
