#!/bin/sh
#run update

set -x

/sbin/modprobe zfs

#Import pool named rpool without mountpoint
zpool import rpool -N

#Set mountpoint of rpool to "none"
zfs set mountpoint=none rpool

#Get the name of volume with mountpoint in /
#exmple rpool/ROOT/plutarcolab
ROOT_VOLUME=$(zfs get mountpoint | awk  '$3=="/" {print $1}')

#Get the name of default image 
#example plutarcolab
IMAGE_NAME=$(echo $ROOT_VOLUME | cut -d '/' -f 3)

#Get latest snapshot on this volume
#example rpool/ROOT/plutarco@1530956369
LAST_SNAP=$(zfs list -t snapshot -o name -s creation -r ${ROOT_VOLUME} | tail -1)

#ROLLBACK to latest snapshot
zfs rollback ${LAST_SNAP}

#Get only the name of snaspshot
#example 1530956369
LAST_SNAP_TS=$(echo $LAST_SNAP | cut -d '@' -f 2)

## Mount remote increments directory

# Get remote server
for x in /run/net-"${DEVICE}".conf /run/net-*.conf /tmp/net-*conf; do
    if [ -e $x ]; then
        . ${x}
        export $ROOTSERVER
    fi
done 

#make mount point in to initramfs 
mkdir /mnt

#mount updates
mount.nfs $ROOTSERVER:/LNPZFS/livenet/increases /mnt/

#check how many update need to install
N_UPDATES=0
for x in `ls /mnt/$IMAGE_NAME/*.gz`
do
    let "N_UPDATES += 1"
done
echo $N_UPDATES


#Install all updates
N_UPDATES = 0
N_UPDATE_OK = 0


for UPDATE_FILE in `ls /mnt/$IMAGE_NAME/*.gz`
do
      ##old  NUMBERVALUE=$(echo ${UPDATE_FILE} | cut -d '.' -f 1 | rev | cut -d '/' -f 1 | rev)
      NUMBERVALUE=$(echo ${UPDATE_FILE} | cut -d '.' -f 1 )
      NUMBERVALUE=${NUMBERVALUE##*/}

        let "N_UPDATES += 1"
        if [ ${NUMBERVALUE} -gt ${LAST_SNAP_TS} ]; then
            start_time=$(date +%s)
            echo ${UPDATE_FILE}  "is more recent than " $LAST_SNAP ", now we can install it..."
            zcat ${UPDATE_FILE} | zfs receive -F ${ROOT_VOLUME}
            end_time=$(date +%s)
            sleep 1
            LAST_SNAP=$(zfs list -t snapshot -o name -s creation -r ${ROOT_VOLUME} | tail -1)
            LAST_SNAP_TS=$(echo $LAST_SNAP | cut -d '@' -f 2)
            echo "The system have install ${UPDATE_FILE} on the volume ${ROOT_VOLUME}, the most recent snapshot of the volume is ${LAST_SNAP}"
            echo "elapsed time: $(( $((end_time - start_time))/60 )) min."
            let "N_UPDATE_OK += 1"
            echo "Install next update"
            sleep 1
        fi
    
done

cd /

umount /mnt
if [[ $(mount | grep /mnt/ | wc -l) -gt 0 ]]; then
#if there are some promblems with umount, bye bye
    umount -lf /mnt/
fi

zfs set mountpoint=/mnt ${ROOT_VOLUME}
zfs mount ${ROOT_VOLUME}
mount --rbind /dev /mnt/dev
mount --rbind /proc /mnt/proc
mount --rbind /sys /mnt/sys


DISK=/dev/sda 
  [ -b $DISK ] || DISK=/dev/vda 
  if [ ! -b $DISK ]; then
    echo "NO vda o sda found"
    exit 1
  fi

chroot /mnt /bin/bash -c "grub-install $DISK"
chroot /mnt /bin/bash -c "update-grub" 


umount /proc /mnt/proc
umount /mnt/sys
umount /mnt/dev/pts
umount /mnt/dev
umount /mnt/

zfs set mountpoint=/ ${ROOT_VOLUME}

mount | grep -v zfs | tac | awk '/\/mnt/ {print $3}' | xargs -i{} umount -lf {}

zpool export rpool

exit 0

