#!/bin/bash


TIMEOUT_NAC=10

#exec > /tmp/start 2>&1
set -x

. /etc/livenet/livenet.conf

set +e

[ "${livenet_8021x}" = "true" ] || exit 0

grep -q "^${PAM_USER}:" /etc/passwd
[ $? = 0 ] && exit 0 # local user, no NAC

WPACONF=/run/user/${PAM_USER}/wpa_supplicant.conf

if [ "${PAM_SERVICE}" = "login" ] || [ "${PAM_SERVICE}" = "gdm-password" ] || [ "${PAM_SERVICE}" = "lightdm" ]; then
    if [ -f ${WPACONF} ]; then
#	systemctl stop autofs
        echo "802.1x enabled" | logger
        umount -f ${HOME} >/dev/null 2>&1
        wpa_supplicant -B -c ${WPACONF} -D wired -i eno1 -W
        log_lightdm "AUTENTICAZIONE DI RETE"
        echo logoff | wpa_cli
        sleep 4
        echo logon | wpa_cli
       
        i=0 
        while [ 1 ]; do
            wpa_cli status | grep "EAP state" | grep SUCCESS
            if [ $? = 0 ]; then
                break
            fi

            i=$((i+1))
            if [ $i -gt ${TIMEOUT_NAC} ]; then
                echo "wpa_supplicant died" | logger 
                killall wpa_supplicant
                netplan apply

                # pam exit at login (see pam.d/common-session)
                exit 100
            fi
            echo "wpa_supplicant sleep" | logger 
            sleep 1
        done
        rm -f ${WPACONF}
        log_lightdm "ACQUISIZIONE INDIRIZZO IP ..."
        netplan apply && log_lightdm "ACQUISIZIONE IP RIUSCITA"
#        sleep 10
#	systemctl start autofs
#	sleep 5
    fi
fi

exit 0
