#!/bin/sh -e
# initramfs hook for livenet

PREREQ=""

# Output pre-requisites
prereqs()
{
       echo "$PREREQ"
}

case "$1" in
    prereqs)
       prereqs
       exit 0
       ;;
esac

. /usr/share/initramfs-tools/hook-functions

rm ${DESTDIR}/bin/cpio # importante! altrimenti rimane un cpio troppo semplificato
copy_exec /bin/cpio /bin

mkdir -p ${DESTDIR}/conf
cp /etc/livenet/livenet.conf ${DESTDIR}/conf
[ -f /etc/livenet/livenet.conf.override ] && cp /etc/livenet/livenet.conf.override ${DESTDIR}/conf
cp /etc/initramfs-tools/scripts/functions-livenet ${DESTDIR}/conf

manual_add_modules aufs
manual_add_modules overlayfs
auto_add_modules net
#auto_add_modules nfs4
#force_load nfs4

# pulizia di firmware non necessario e pesante
set +e
rm -f ${DESTDIR}/lib/firmware/* >/dev/null 2>&1
set -e

### qui sotto andrebbe commentato in produzione ###

# tastiera italiana in initram
# attivata da do_debug_shell (loadkeys /etc/boottime.kmap.gz)
#cp -au /etc/console-setup/cached_UTF-8_del.kmap.gz ${DESTDIR}/etc/boottime.kmap.gz

# nfs4
copy_exec /usr/sbin/rpc.idmapd /bin
copy_exec /sbin/mount.nfs /bin
cp -au /etc/netconfig ${DESTDIR}/etc/netconfig

#cat > ${DESTDIR}/etc/passwd <<EOF
#nobody::65534:65534:nobody:/nonexistent:/bin/sh
#EOF
#cat > ${DESTDIR}/etc/group <<EOF
#nogroup:x:65534:
#EOF

# debug purpose ################
# ricordati di mettere FRAMEBUFFER=n in /etc/initramfs-tools/conf.d/splash
#copy_exec /sbin/ifconfig
copy_exec /sbin/lsmod /bin
#copy_exec /usr/bin/lspci /bin
#################################

# wireless #####################
#copy_exec /sbin/iwconfig
#copy_exec /sbin/iwlist
#copy_exec /sbin/iwpriv
#copy_exec /sbin/iwevent
#copy_exec /sbin/iwgetid
#copy_exec /sbin/iwspy
#copy_exec /usr/sbin/rfkill
#cp -au /lib/firmware/iwl*-[13].ucode ${DESTDIR}/lib/firmware
#################################
